package com.hyc.entity;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.id
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.name
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.manager_code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    private String managerCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.id
     *
     * @return the value of t_dept.id
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.id
     *
     * @param id the value for t_dept.id
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.name
     *
     * @return the value of t_dept.name
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.name
     *
     * @param name the value for t_dept.name
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.code
     *
     * @return the value of t_dept.code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.code
     *
     * @param code the value for t_dept.code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.manager_code
     *
     * @return the value of t_dept.manager_code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public String getManagerCode() {
        return managerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.manager_code
     *
     * @param managerCode the value for t_dept.manager_code
     *
     * @mbg.generated Sat Jun 15 21:58:00 CST 2019
     */
    public void setManagerCode(String managerCode) {
        this.managerCode = managerCode == null ? null : managerCode.trim();
    }
}